/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSociety: typeof import('./src/components/pages/aboutSociety.vue')['default']
    BuildTeam: typeof import('./src/components/pages/buildTeam.vue')['default']
    ClassesCenter: typeof import('./src/components/pages/classesCenter.vue')['default']
    Detail1: typeof import('./src/components/pages/society-details/detail1.vue')['default']
    Detail2: typeof import('./src/components/pages/society-details/detail2.vue')['default']
    Detail3: typeof import('./src/components/pages/society-details/detail3.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    Header: typeof import('./src/components/header.vue')['default']
    MasterRobot: typeof import('./src/components/masterRobot.vue')['default']
    PracticeCenter: typeof import('./src/components/pages/practiceCenter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioSimulatio: typeof import('./src/components/pages/scenarioSimulatio.vue')['default']
    Sign_in: typeof import('./src/components/pages/sign/sign_in.vue')['default']
    Sign_up: typeof import('./src/components/pages/sign/sign_up.vue')['default']
    Study: typeof import('./src/components/study.vue')['default']
    UserCenter: typeof import('./src/components/pages/userCenter.vue')['default']
  }
}
